class ENV:
    G_NEWS_API_KEY = "G_NEWS_API_KEY"
    JSON_OUT_DIR = "JSON_OUT_DIR"
    TWITTER_API_KEY_SECRET = "TWITTER_API_KEY_SECRET"
    TWITTER_API_KEY = "TWITTER_API_KEY"
    TWITTER_BEARER_TOKEN = "TWITTER_BEARER_TOKEN"

